### create University
POST http://localhost:3000/universities
Content-Type: application/json

{
    "domains": ["claeh.edu.uy"], 
    "alpha_two_code": "UY", 
    "country": "Uruguay", 
    "web_pages": ["http://www.claeh.edu.uy/"], 
    "name": "Insituto Universitario - Centro Latinoamericano de Economia Humana - IU Claeh"
}

### get all
GET http://localhost:3000/universities

### get by page
GET http://localhost:3000/universities/s?country=Brazil&page=0

### get by id
GET http://localhost:3000/universities/55153a8014829a865bbf700d

### edit by id
PATCH http://localhost:3000/universities/507f191e810c19729de860ea
Content-Type: application/json

{
    "domains": ["teste"], 
    "alpha_two_code": "te", 
    "web_pages": ["http://www.teste.com"], 
    "name": "Insituto Universitario do teste"
}

### delete by id
DELETE http://localhost:3000/universities/632f4439d764db069af0b5f7

### populate all
POST http://localhost:3000/database

### delete all
DELETE http://localhost:3000/database